name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [ 1.6, 1.8, 1.9 ]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}

      - name: Setup env variables
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          export GO111MODULE=on
          export GOPATH=~/go

      - name: Download dependencies ğŸ’¿
        run: |
          go mod download
          go mod vendor
          go mod verify

      - name: Run tests
        run: go test -v .

      - name: Run build ğŸ”¨
        run: go build .